### ISSUE TITLE
Creating the client (written manually)

### ISSUE THREAD

**Issue by pitaslayer** [Bplotka/unity-grpc#1]
Good Afternoon,

First of all, thank you for doing this repository, it was the thing that I need for my project (Unity C# - python). It was a big help for a beginner like me.

However I'm having a problem. All the tutorial went good with no problems, but now I'm trying to create my own protos and generate the new files. And I didn't understand how to create manually the client grpc file. 

For one of examples that I'm following, the .proto is like this:

enum Sentiment {
    HAPPY = 0;
    SLEEPY = 1;
    ANGRY = 2;
}

message HelloRequest {
    string name = 1;
    int32 age = 2;
    Sentiment sentiment = 5;
}

message HelloResponse {
    string greeting = 1;
}

service GreetingService {
    rpc greeting(HelloRequest) returns (HelloResponse);
}

Can you guide me how to do it or give me some points of knowledge?

**Comment by bwplotka** [comment]
Sure. For your own project you can just copy & tweak all protobuf_gen scripts to use it with your current project directories. However, the easiest way will be to just reuse example client, since I have all scripts adjusted for it. 

* Copy this proto to let's say to `example\proto\pitaslayer\greeter.proto`
Make sure you add package and proto version like:
```
syntax = "proto3";

package pitaslayer;
```

* Run `bash example/protogen_csharp.sh`

Now you should have `example\csharp-client\Model\pitaslayer\Greeter.cs` file generated.

* Go to unity, drag & drop the `example/csharp-client` to unity
* Open `csharp-client/GreeterClient.cs`

Basically now you need to add a method that will reuse `DefaultCallInvoker` class.
Since you have Unary call (no streaming), you can use blocking Call if you want, like this:
```
 public Pitaslayer.HelloResponse greeting(GrpcCancellationTokenSource ctx, Pitaslayer.HelloRequest req)
        {
            return this.BlockingUnaryCall<Pitaslayer.HelloRequest, Pitaslayer.HelloResponse>(
                    // Your protobufs message and response as T1, T2.
                    new Method<Pitaslayer.HelloRequest, Pitaslayer.HelloResponse>(
                        // MethodType: Unary, ClientStreaming, ServerStreaming or DuplexStreaming (Bidirectional stream).
                        MethodType.Unary,
                        // This is bit manual, but basically get from your .proto service:
                        // <package name>.<service name>
                        "pitaslayer.GreetingService ",
                        // <method name after "rpc" in your service>
                        "greeting",
                        // Serialization definition for request.
                        new ProtoMarshaller<Pitaslayer.HelloRequest>(Pitaslayer.HelloRequest.Parser),
                         // Serialization definition for respone.
                        new ProtoMarshaller<Pitaslayer.HelloResponse>(Pitaslayer.HelloResponse.Parser)
                    ),
                    this.host,
                    new CallOptions(cancellationToken: new GrpcCancellationToken(ctx)),
                    req
                );
        }
```

Now you can just invoke:
```
var c = new Example.Client(....);
response  = c.greeting(ctx, new Pitslayer.HelloRequest{ ... });
```

You can easily make this call async, but this is more difficult, so if your are beginner just go for blocking.
Hope I helped (:

**Comment by bwplotka** [comment]
I extended repo tutorial to include more details about manually written code. (:

**Comment by pitaslayer** [comment]
Thank you very much. I will follow you instructions.
Just another question.

There is any problems two different version of protoc? In this case 3.0.0 is used to build the Unity Project files however for the python server, the protoc version is the latest. Will be any problems?

**Comment by bwplotka** [comment]
If all of them are 3.x.x, it should be fine.

**Comment by pitaslayer** [comment]
Ok ty very much for your support!

Regarding this issue, everything is fixed!
